### ISSUE TITLE
403 forbidden on puppet + choria interaction

### ISSUE THREAD

**Issue by bastelfreak** [choria-io/mcollective-choria#253]
Hi,
I'm having two weird issues. `mco choria request_cert` returned a 403 http error. I'm not 100% which service returned that. I assume it was the puppetdb API, but I didn't find any 403 errors in my puppetserver.log. Requesting a cert with `puppet agent -t --server=$server --certname=mco.mcollective` worked, and mco is happily using this.

----

Another issue that is probably related:

```
$ mco puppet status --dm=choria -v
Discovering hosts using the choria method .... 
The puppet application failed to run: 403 "Forbidden"

403 "Forbidden" (Net::HTTPServerException)
	from /opt/puppetlabs/puppet/lib/ruby/2.1.0/net/http/response.rb:119:in `error!'  <----
	from /opt/puppetlabs/puppet/lib/ruby/2.1.0/net/http/response.rb:128:in `value'
	from /opt/puppetlabs/puppet/lib/ruby/2.1.0/net/http.rb:915:in `connect'
	from /opt/puppetlabs/puppet/lib/ruby/2.1.0/net/http.rb:863:in `do_start'
	from /opt/puppetlabs/puppet/lib/ruby/2.1.0/net/http.rb:852:in `start'
	from /opt/puppetlabs/puppet/lib/ruby/2.1.0/net/http.rb:1375:in `request'
	from /opt/puppetlabs/mcollective/plugins/mcollective/util/choria.rb:283:in `pql_query'
	from /opt/puppetlabs/mcollective/plugins/mcollective/discovery/choria.rb:37:in `discover'
	from /opt/puppetlabs/mcollective/plugins/mcollective/discovery/choria.rb:8:in `discover'
	from /opt/puppetlabs/puppet/lib/ruby/vendor_ruby/mcollective/discovery.rb:134:in `discover'
	from /opt/puppetlabs/puppet/lib/ruby/vendor_ruby/mcollective/client.rb:151:in `discover'
	from /opt/puppetlabs/puppet/lib/ruby/vendor_ruby/mcollective/rpc/client.rb:572:in `discover'
	from /opt/puppetlabs/puppet/lib/ruby/vendor_ruby/mcollective/rpc/client.rb:926:in `call_agent'
	from /opt/puppetlabs/puppet/lib/ruby/vendor_ruby/mcollective/rpc/client.rb:279:in `method_missing'
	from /opt/puppetlabs/mcollective/plugins/mcollective/application/puppet.rb:313:in `status_command'
	from /opt/puppetlabs/mcollective/plugins/mcollective/application/puppet.rb:376:in `main'
	from /opt/puppetlabs/puppet/lib/ruby/vendor_ruby/mcollective/application.rb:293:in `run'
	from /opt/puppetlabs/puppet/lib/ruby/vendor_ruby/mcollective/applications.rb:23:in `run'
	from /opt/puppetlabs/bin/mco:33:in `<main>'
```

however, `mco puppet status` works. Everything is runs on up2date centos 7 boxes with selinux. mcollective is in version 2.10.3, puppet in 4.10. Let me know if you need any additional information.

**Comment by bastelfreak** [comment]
```
$ mco choria show_config
Active Choria configuration:

The active configuration used in Choria comes from using Puppet AIO defaults, querying SRV
records and reading configuration files.  The below information shows the completely resolved
configuration that will be used when running MCollective commands

MCollective related:

    MCollective Version: 2.10.3
     Client Config File: /etc/puppetlabs/mcollective/client.cfg
     Active Config File: /etc/puppetlabs/mcollective/client.cfg
      Plugin Config Dir: /etc/puppetlabs/mcollective/plugin.d
      Using SRV Records: false
              Federated: false
             SRV Domain: 
     Middleware Servers: server02:4222

Puppet related:

       Puppet Server: server01:8140
     PuppetCA Server: server01:8140
     PuppetDB Server: server01:8140
      Facter Command: /opt/puppetlabs/bin/facter
       Facter Domain: 

SSL setup:

     Valid SSL Setup: yes
            Certname: mco.mcollective
       SSL Directory: /home/mco/.puppetlabs/etc/puppet/ssl (found)
  Client Public Cert: /home/mco/.puppetlabs/etc/puppet/ssl/certs/mco.mcollective.pem (found)
  Client Private Key: /home/mco/.puppetlabs/etc/puppet/ssl/private_keys/mco.mcollective.pem (found)
             CA Path: /home/mco/.puppetlabs/etc/puppet/ssl/certs/ca.pem (found)
            CSR Path: /home/mco/.puppetlabs/etc/puppet/ssl/certificate_requests/mco.mcollective.pem (found)

Active Choria configuration settings as found in configuration files:

    choria.use_srv_records: false
  choria.puppetserver_host: server01
  choria.puppetserver_port: 8140
      choria.puppetca_host: server01
      choria.puppetca_port: 8140
      choria.puppetdb_host: server02
      choria.puppetdb_port: 8081
   choria.middleware_hosts: server02.:422
```

hostnames are sanitized.

**Comment by ripienaar** [comment]
hmm, so I would guess what happened is somehow when the `request_cert` failed it made ssl files on disk but perhaps wrong, or invalid, or against a wrong CA or something along those lines.

And now it tries to talk to the PuppetDB SSL port and it rightly refuses the connection as its from a unknown CA.

what does .... and there you just put what I wanted to ask good job.

so I guess we should validate `/home/mco/.puppetlabs/etc/puppet/ssl/certs/mco.mcollective.pem` is legit, try `openssl x509 -in /home/mco/.puppetlabs/etc/puppet/ssl/certs/mco.mcollective.pem -text` and see if its a legit cert and right issuer signed it etc?

I don't *think* that I attempt to load those certs in `show_config`, I should and make sure they're valid

**Comment by bastelfreak** [comment]
openssl says it is a valid certificate. also `request_cert` didn't create any files in ~/.puppetlabs, just empty directories.

**Comment by ripienaar** [comment]
nah `request_cert` creates all those SSL files, first the request and private key and later the cert and along the way the ca.  It's the whole puppet agent --test new cert/sign dance.

**Comment by ripienaar** [comment]
So something went very wrong with request cert, hard to say what without seeing it, but I'd clean/revoke that cert on your master (if you signed it ever even) and delete these SSL files and run `request_cert` again and show me what happens :)

**Comment by ripienaar** [comment]
Does it all work with the normal mco discovery method?

**Comment by bastelfreak** [comment]
Sorry, I'm pretty new to the mco CLI. How do I know I use the normal method? Commands that are working:
* `mco ping`
* `mco inventory $fqdn`
* `mco puppet status`
* `mco serfice status $service`

I will provision a new box later to test the ssl cert generation

**Comment by ripienaar** [comment]
@bastelfreak hmm, thats super weird then, in that case I think this should work.  The error in question best I can tell is PuppetDB saying you're not allowed to query - which suggests its bad SSL or setup like limiting which IPs can connect to PuppetDB or similar.

Your SSL is probably fine.

I installed the puppet-client-tools package and with this config:

```
{
  "puppetdb": {
    "server_urls": "https://puppet:8081",
    "cacert": "/home/rip/.puppetlabs/etc/puppet/ssl/certs/ca.pem",
    "cert": "/home/rip/.puppetlabs/etc/puppet/ssl/certs/rip.mcollective.pem",
    "key": "/home/rip/.puppetlabs/etc/puppet/ssl/private_keys/rip.mcollective.pem"
  }
}
```

in `~/.puppetlabs/client-tools/puppetdb.conf` I can do things like `puppet query 'nodes[certname] {}'`

If you can get that working then so should mco, and it should be a good way to verify independent from MCO where the problem might lie?

**Comment by bastelfreak** [comment]
I now have a testbox available:

```
$ mco choria request_cert -v

The choria application failed to run: 403 "Forbidden"

403 "Forbidden" (Net::HTTPServerException)
	from /opt/puppetlabs/puppet/lib/ruby/2.1.0/net/http/response.rb:119:in `error!'  <----
	from /opt/puppetlabs/puppet/lib/ruby/2.1.0/net/http/response.rb:128:in `value'
	from /opt/puppetlabs/puppet/lib/ruby/2.1.0/net/http.rb:915:in `connect'
	from /opt/puppetlabs/puppet/lib/ruby/2.1.0/net/http.rb:863:in `do_start'
	from /opt/puppetlabs/puppet/lib/ruby/2.1.0/net/http.rb:852:in `start'
	from /opt/puppetlabs/puppet/lib/ruby/2.1.0/net/http.rb:1375:in `request'
	from /opt/puppetlabs/mcollective/plugins/mcollective/util/choria.rb:735:in `fetch_ca'
	from /opt/puppetlabs/mcollective/plugins/mcollective/application/choria.rb:101:in `request_cert_command'
	from /opt/puppetlabs/mcollective/plugins/mcollective/application/choria.rb:79:in `main'
	from /opt/puppetlabs/puppet/lib/ruby/vendor_ruby/mcollective/application.rb:293:in `run'
	from /opt/puppetlabs/puppet/lib/ruby/vendor_ruby/mcollective/applications.rb:23:in `run'
	from /opt/puppetlabs/bin/mco:33:in `<main>'
$ puppet agent -t --server=server01 --certname=testcert.mcollective
Info: Creating a new SSL key for testcert.mcollective
Info: Caching certificate for ca
Info: csr_attributes file loading from /home/testcert/.puppetlabs/etc/puppet/csr_attributes.yaml
Info: Creating a new SSL certificate request for testcert.mcollective
Info: Certificate Request fingerprint (SHA256): F6:05:2A:1C:06:B0:A1:6C:A3:04:D5:FE:FE:B7:8B:C1:95:4A:9A:6F:D4:54:8B:FB:0B:51:47:E0:4C:C0:A4:F9
Info: Caching certificate for testcert.mcollective
Info: Caching certificate_revocation_list for ca
Info: Caching certificate for ca
Warning: Unable to fetch my node definition, but the agent run will continue:
Warning: Error 500 on SERVER: Server Error: Failed to find testcert.mcollective via exec: Execution of '/etc/puppetlabs/puppet/node.rb testcert.mcollective' returned 1: 
Info: Retrieving pluginfacts
Notice: /File[/home/testcert/.puppetlabs/opt/puppet/cache/facts.d]/mode: mode changed '0775' to '0755'
Info: Retrieving plugin
Notice: /File[/home/testcert/.puppetlabs/opt/puppet/cache/lib/facter]/ensure: created
...

$ mco choria show_config
Active Choria configuration:

The active configuration used in Choria comes from using Puppet AIO defaults, querying SRV
records and reading configuration files.  The below information shows the completely resolved
configuration that will be used when running MCollective commands

MCollective related:

    MCollective Version: 2.10.3
     Client Config File: /etc/puppetlabs/mcollective/client.cfg
     Active Config File: /etc/puppetlabs/mcollective/client.cfg
      Plugin Config Dir: /etc/puppetlabs/mcollective/plugin.d
      Using SRV Records: false
              Federated: false
             SRV Domain: ***
     Middleware Servers: server02:4222

Puppet related:

       Puppet Server: server01:8140
     PuppetCA Server: server01:8140
     PuppetDB Server: server01:8140
      Facter Command: /opt/puppetlabs/bin/facter
       Facter Domain: ***

SSL setup:

     Valid SSL Setup: yes
            Certname: testcert.mcollective
       SSL Directory: /home/testcert/.puppetlabs/etc/puppet/ssl (found)
  Client Public Cert: /home/testcert/.puppetlabs/etc/puppet/ssl/certs/testcert.mcollective.pem (found)
  Client Private Key: /home/testcert/.puppetlabs/etc/puppet/ssl/private_keys/testcert.mcollective.pem (found)
             CA Path: /home/testcert/.puppetlabs/etc/puppet/ssl/certs/ca.pem (found)
            CSR Path: /home/testcert/.puppetlabs/etc/puppet/ssl/certificate_requests/testcert.mcollective.pem (found)

Active Choria configuration settings as found in configuration files:

    choria.use_srv_records: false
  choria.puppetserver_host: server01
  choria.puppetserver_port: 8140
      choria.puppetca_host: server01
      choria.puppetca_port: 8140
      choria.puppetdb_host: server02
      choria.puppetdb_port: 8081
   choria.middleware_hosts: server02:4222
```

there is a difference between the puppetdb host/port in the puppet section vs choria section. on server01 is only my master + CA running, the puppetdb moved months ago to server02.

It is configured correctly in hiera, not sure where the wrong value is coming from:

```yaml
---
mcollective_choria::config:
  use_srv_records: false
  puppetserver_host: 'server01'
  puppetserver_port: 8140
  puppetca_host: 'server01'
  puppetca_port: 8140
  puppetdb_host: 'server02'
  puppetdb_port: 8081
  middleware_hosts: 'server02:4222'
mcollective::site_policies:
- action: "allow"
  callers: "choria=mco.mcollective"
  actions: "*"
  facts: "*"
  classes: "*"
mcollective::client: false
mcollective::server: true
mcollective::server_config:
  rpcauditprovider: 'choria'
  plugin.rpcaudit.logfile: '/var/log/puppetlabs/choria-audit.log'
```

**Comment by ripienaar** [comment]
The incorrect output from show_config is a bug #244

OK, so request_cert is failing and that leaves it all a bit screwed.  However request_cert failing is really weird since you should be able to fetch the CA without auth.

on mine for example `curl https://puppet:8140/puppet-ca/v1/certificate/ca -k` works a charm, what does your CA say about that?

**Comment by bastelfreak** [comment]
ooookey ... 
so I did a lot of debugging today. the http_poxy and https_proxy env var is set on all boxes. Turns out that the no_proxy env varible wasn't set correctly. The squid returns 403 for internal requests. I added my puppetserver/ca to the no_proxy variable and everything seems to work. I'm not sure why puppet-agent worked, maybe it ignores proxy env var settings.

**Comment by ripienaar** [comment]
lol that sux, sorry this has been such a nightmare, glad you got there in the end :)
