### ISSUE TITLE
Having trouble requesting a cert on a different ca_port

### ISSUE THREAD

**Issue by jeefberkey** [choria-io/mcollective-choria#265]
I'm trying to set up Choria, and am having some issues requesting user certs. We run our puppet CA on a different port than our puppetserver, and it doesn't look like Choria is handling it appropriately.

Here's the output when I try to run `request_cert`
```
SSL_connect SYSCALL returned=5 errno=0 state=unknown state (OpenSSL::SSL::SSLError)
	from /opt/puppetlabs/puppet/lib/ruby/2.1.0/net/http.rb:923:in `connect'  <----
	from /opt/puppetlabs/puppet/lib/ruby/2.1.0/net/http.rb:923:in `block in connect'
	from /opt/puppetlabs/puppet/lib/ruby/2.1.0/timeout.rb:75:in `timeout'
	from /opt/puppetlabs/puppet/lib/ruby/2.1.0/net/http.rb:923:in `connect'
	from /opt/puppetlabs/puppet/lib/ruby/2.1.0/net/http.rb:863:in `do_start'
	from /opt/puppetlabs/puppet/lib/ruby/2.1.0/net/http.rb:852:in `start'
	from /opt/puppetlabs/puppet/lib/ruby/2.1.0/net/http.rb:1375:in `request'
	from /opt/puppetlabs/mcollective/plugins/mcollective/util/choria.rb:802:in `fetch_ca'
	from /opt/puppetlabs/mcollective/plugins/mcollective/application/choria.rb:101:in `request_cert_command'
	from /opt/puppetlabs/mcollective/plugins/mcollective/application/choria.rb:79:in `main'
	from /opt/puppetlabs/puppet/lib/ruby/vendor_ruby/mcollective/application.rb:293:in `run'
	from /opt/puppetlabs/puppet/lib/ruby/vendor_ruby/mcollective/applications.rb:23:in `run'
	from /opt/puppetlabs/bin/mco:33:in `<main>'
debug 2017/05/08 14:59:28: pluginmanager.rb:83:in `[]' Returning cached plugin connector_plugin with class MCollective::Connector::Nats
```
And the debug log above that says:
```
debug 2017/05/08 14:59:28: choria.rb:231:in `https' Creating new HTTPS connection to puppet:8140
```
I have this set in common.yaml:
```
iptables::ports:
  4222:
  4223:
  8222:

mcollective_choria::config:
  use_srv_records: false
  puppetca_port: 8141

classes:
  - mcollective
```
and this in my server.yaml:
```
mcollective::client: true

classes:
  - nats
```
Which leads me to believe that there's a bug reading the ca_port configuration option. The trace in the first snippet points to the `fetch_ca` function, which points to port 8140, even though I have 8141 set.

Thanks.

**Comment by ripienaar** [comment]
Can you show `mco choria show_config` please?

**Comment by ripienaar** [comment]
and also show same as root

**Comment by jeefberkey** [comment]
```
[root@puppet production]# mco choria show_config
Active Choria configuration:

The active configuration used in Choria comes from using Puppet AIO defaults, querying SRV
records and reading configuration files.  The below information shows the completely resolved
configuration that will be used when running MCollective commands

MCollective related:

    MCollective Version: 2.9.1
         Choria Version: 0.0.26
     Client Config File: /etc/puppetlabs/mcollective/client.cfg
     Active Config File: /etc/puppetlabs/mcollective/client.cfg
      Plugin Config Dir: /etc/puppetlabs/mcollective/plugin.d
      Using SRV Records: false
              Federated: false
             SRV Domain: example.com
     Middleware Servers: puppet:42222

Puppet related:

       Puppet Server: puppet:8140
     PuppetCA Server: puppet:8140
     PuppetDB Server: puppet:8081
      Facter Command: /opt/puppetlabs/bin/facter
       Facter Domain: example.com

SSL setup:

     Valid SSL Setup: yes
            Certname: puppet.example.com
       SSL Directory: /etc/puppetlabs/puppet/ssl (found)
  Client Public Cert: /etc/puppetlabs/puppet/ssl/certs/puppet.example.com.pem (found)
  Client Private Key: /etc/puppetlabs/puppet/ssl/private_keys/puppet.example.com.pem (found)
             CA Path: /etc/puppetlabs/puppet/ssl/certs/ca.pem (found)
            CSR Path: /etc/puppetlabs/puppet/ssl/certificate_requests/puppet.example.com.pem (absent)

Active Choria configuration settings as found in configuration files:

  choria.use_srv_records: false
    choria.puppetca_port: 8141
```

```
[vagrant@puppet ~]$ mco choria show_config
Active Choria configuration:

The active configuration used in Choria comes from using Puppet AIO defaults, querying SRV
records and reading configuration files.  The below information shows the completely resolved
configuration that will be used when running MCollective commands

MCollective related:

    MCollective Version: 2.9.1
         Choria Version: 0.0.26
     Client Config File: /etc/puppetlabs/mcollective/client.cfg
     Active Config File: /etc/puppetlabs/mcollective/client.cfg
      Plugin Config Dir: /etc/puppetlabs/mcollective/plugin.d
      Using SRV Records: false
              Federated: false
             SRV Domain: example.com
     Middleware Servers: puppet:42222

Puppet related:

       Puppet Server: puppet:8140
     PuppetCA Server: puppet:8140
     PuppetDB Server: puppet:8081
      Facter Command: /opt/puppetlabs/bin/facter
       Facter Domain: example.com
SSL setup:

     Valid SSL Setup: no run 'mco choria request_cert'
            Certname: vagrant.mcollective
       SSL Directory: /home/vagrant/.puppetlabs/etc/puppet/ssl (found)
  Client Public Cert: /home/vagrant/.puppetlabs/etc/puppet/ssl/certs/vagrant.mcollective.pem (absent)
  Client Private Key: /home/vagrant/.puppetlabs/etc/puppet/ssl/private_keys/vagrant.mcollective.pem (absent)
             CA Path: /home/vagrant/.puppetlabs/etc/puppet/ssl/certs/ca.pem (absent)
            CSR Path: /home/vagrant/.puppetlabs/etc/puppet/ssl/certificate_requests/vagrant.mcollective.pem (absent)

Active Choria configuration settings as found in configuration files:

  choria.use_srv_records: false
    choria.puppetca_port: 8141
```

**Comment by ripienaar** [comment]
Looks like a big yes. It does not use the puppetca_port variable at all the port is hard coded. Will fix

**Comment by jeefberkey** [comment]
Awesome, thanks for the quick response.

**Comment by jeefberkey** [comment]
This fixed my issue, thanks.
