### ISSUE TITLE
Playbook command not working due to missing etcd_data_store file

### ISSUE THREAD

**Issue by dnlsng** [choria-io/mcollective-choria#292]
```
error 2017/06/23 10:17:18: pluginmanager.rb:171:in `rescue in loadclass' Failed to load MCollective::Util::Playbook: cannot load such fil
e -- /opt/puppetlabs/mcollective/plugins/mcollective/util/playbook/data_stores/etcd_data_store
/opt/puppetlabs/mcollective/plugins/mcollective/util/playbook/data_stores.rb:4:in `require_relative': cannot load such file -- /opt/puppe
tlabs/mcollective/plugins/mcollective/util/playbook/data_stores/etcd_data_store (LoadError)
        from /opt/puppetlabs/mcollective/plugins/mcollective/util/playbook/data_stores.rb:4:in `<top (required)>'
        from /opt/puppetlabs/mcollective/plugins/mcollective/util/playbook.rb:8:in `require_relative'
        from /opt/puppetlabs/mcollective/plugins/mcollective/util/playbook.rb:8:in `<top (required)>'
        from /opt/puppetlabs/puppet/lib/ruby/vendor_ruby/mcollective/pluginmanager.rb:169:in `load'
        from /opt/puppetlabs/puppet/lib/ruby/vendor_ruby/mcollective/pluginmanager.rb:169:in `loadclass'
        from /opt/puppetlabs/puppet/lib/ruby/vendor_ruby/mcollective/util.rb:234:in `loadclass'
        from /opt/puppetlabs/mcollective/plugins/mcollective/application/playbook.rb:45:in `playbook'
        from /opt/puppetlabs/mcollective/plugins/mcollective/application/playbook.rb:57:in `run'
        from /opt/puppetlabs/puppet/lib/ruby/vendor_ruby/mcollective/applications.rb:23:in `run'
        from /opt/puppetlabs/bin/mco:33:in `<main>'
```

It just looks like "util/playbook/data_stores/etcd_data_store.rb" is missing from mcollective_choria::client_files in data/plugins.yaml.

**Comment by ripienaar** [comment]
yes, does seem the way :(
