### ISSUE TITLE
Federation broker fails to reconnect to NATS broker

### ISSUE THREAD

**Issue by mateusz-gozdek-sociomantic** [choria-io/mcollective-choria#299]
I experienced few times the problem, when with problematic network, federation broker was disconnected from nats broker several times and at some point it stopped connecting. It just froze for more than 6h.

Here is the log I got, with filtered out INFO. It shows that it was able to reconnect several times, but at some point, it stopped. I will try to gather more information next time it happens.

Logs contains reference to localhost, however real connecton was over the internet, with pretty high latency and packet loss.

```
# Logfile created on 2017-07-05 23:43:47 +0000 by logger.rb/53938
E, [2017-07-06T00:56:25.223165 #28694] ERROR -- : natswrapper.rb:145:in `block in start' Error in NATS connection: Errno::ECONNRESET: Connection reset by peer
W, [2017-07-06T00:56:25.223613 #28694]  WARN -- : natswrapper.rb:138:in `block in start' Disconnected from NATS: Errno::ECONNRESET: Connection reset by peer
E, [2017-07-06T00:56:31.838333 #28694] ERROR -- : natswrapper.rb:145:in `block in start' Error in NATS connection: OpenSSL::SSL::SSLError: SSL_connect returned=1 errno=0 state=unknown state: wrong version number
E, [2017-07-06T00:56:35.153601 #28694] ERROR -- : natswrapper.rb:145:in `block in start' Error in NATS connection: NATS::IO::SocketTimeoutError: NATS::IO::SocketTimeoutError
W, [2017-07-06T00:56:40.071526 #28694]  WARN -- : natswrapper.rb:131:in `block in start' Reconnected after connection failure: nats://nats.localhost:4222
E, [2017-07-06T00:57:18.803154 #28694] ERROR -- : natswrapper.rb:145:in `block in start' Error in NATS connection: Errno::ECONNRESET: Connection reset by peer
W, [2017-07-06T00:57:18.803383 #28694]  WARN -- : natswrapper.rb:138:in `block in start' Disconnected from NATS: Errno::ECONNRESET: Connection reset by peer
E, [2017-07-06T00:57:21.805870 #28694] ERROR -- : natswrapper.rb:145:in `block in start' Error in NATS connection: NATS::IO::SocketTimeoutError: NATS::IO::SocketTimeoutError
E, [2017-07-06T00:57:25.602535 #28694] ERROR -- : natswrapper.rb:145:in `block in start' Error in NATS connection: OpenSSL::SSL::SSLError: SSL_connect returned=1 errno=0 state=unknown state: wrong version number
E, [2017-07-06T00:57:34.634710 #28694] ERROR -- : natswrapper.rb:145:in `block in start' Error in NATS connection: OpenSSL::SSL::SSLError: SSL_connect returned=1 errno=0 state=unknown state: wrong version number
W, [2017-07-06T00:57:41.255366 #28694]  WARN -- : natswrapper.rb:131:in `block in start' Reconnected after connection failure: nats://nats.localhost:4222
E, [2017-07-06T00:58:03.871529 #28694] ERROR -- : natswrapper.rb:145:in `block in start' Error in NATS connection: Errno::ECONNRESET: Connection reset by peer
W, [2017-07-06T00:58:03.871712 #28694]  WARN -- : natswrapper.rb:138:in `block in start' Disconnected from NATS: Errno::ECONNRESET: Connection reset by peer
W, [2017-07-06T00:58:08.231330 #28694]  WARN -- : natswrapper.rb:131:in `block in start' Reconnected after connection failure: nats://nats.localhost:4222
E, [2017-07-06T00:58:30.077753 #28694] ERROR -- : natswrapper.rb:145:in `block in start' Error in NATS connection: Errno::ECONNRESET: Connection reset by peer
W, [2017-07-06T00:58:30.077944 #28694]  WARN -- : natswrapper.rb:138:in `block in start' Disconnected from NATS: Errno::ECONNRESET: Connection reset by peer
E, [2017-07-06T00:58:33.718426 #28694] ERROR -- : natswrapper.rb:145:in `block in start' Error in NATS connection: Errno::ECONNRESET: Connection reset by peer - SSL_connect
E, [2017-07-06T00:58:39.708773 #28694] ERROR -- : natswrapper.rb:145:in `block in start' Error in NATS connection: OpenSSL::SSL::SSLError: SSL_connect returned=1 errno=0 state=unknown state: wrong version number
E, [2017-07-06T00:58:47.513892 #28694] ERROR -- : natswrapper.rb:145:in `block in start' Error in NATS connection: NATS::IO::SocketTimeoutError: NATS::IO::SocketTimeoutError
E, [2017-07-06T00:58:52.560602 #28694] ERROR -- : natswrapper.rb:145:in `block in start' Error in NATS connection: OpenSSL::SSL::SSLError: SSL_connect returned=1 errno=0 state=unknown state: wrong version number
W, [2017-07-06T00:58:55.166951 #28694]  WARN -- : natswrapper.rb:131:in `block in start' Reconnected after connection failure: nats://nats.localhost:4222
E, [2017-07-06T00:59:18.717250 #28694] ERROR -- : natswrapper.rb:145:in `block in start' Error in NATS connection: Errno::ECONNRESET: Connection reset by peer
W, [2017-07-06T00:59:18.717552 #28694]  WARN -- : natswrapper.rb:138:in `block in start' Disconnected from NATS: Errno::ECONNRESET: Connection reset by peer
E, [2017-07-06T00:59:22.032920 #28694] ERROR -- : natswrapper.rb:145:in `block in start' Error in NATS connection: NATS::IO::SocketTimeoutError: NATS::IO::SocketTimeoutError
W, [2017-07-06T00:59:27.582750 #28694]  WARN -- : natswrapper.rb:131:in `block in start' Reconnected after connection failure: nats://nats.localhost:4222
E, [2017-07-06T01:00:18.782421 #28694] ERROR -- : natswrapper.rb:145:in `block in start' Error in NATS connection: Errno::ECONNRESET: Connection reset by peer
W, [2017-07-06T01:00:18.782788 #28694]  WARN -- : natswrapper.rb:138:in `block in start' Disconnected from NATS: Errno::ECONNRESET: Connection reset by peer
W, [2017-07-06T01:00:21.868909 #28694]  WARN -- : natswrapper.rb:131:in `block in start' Reconnected after connection failure: nats://nats.localhost:4222
E, [2017-07-06T01:02:54.804998 #28694] ERROR -- : natswrapper.rb:145:in `block in start' Error in NATS connection: Errno::ECONNRESET: Connection reset by peer
W, [2017-07-06T01:02:54.805235 #28694]  WARN -- : natswrapper.rb:138:in `block in start' Disconnected from NATS: Errno::ECONNRESET: Connection reset by peer
W, [2017-07-06T01:03:01.913956 #28694]  WARN -- : natswrapper.rb:131:in `block in start' Reconnected after connection failure: nats://nats.localhost:4222
E, [2017-07-06T01:03:15.942230 #28694] ERROR -- : natswrapper.rb:145:in `block in start' Error in NATS connection: Errno::ECONNRESET: Connection reset by peer
W, [2017-07-06T01:03:15.942572 #28694]  WARN -- : natswrapper.rb:138:in `block in start' Disconnected from NATS: Errno::ECONNRESET: Connection reset by peer
E, [2017-07-06T01:03:19.738356 #28694] ERROR -- : natswrapper.rb:145:in `block in start' Error in NATS connection: OpenSSL::SSL::SSLError: SSL_connect returned=1 errno=0 state=unknown state: wrong version number
E, [2017-07-06T01:03:23.749295 #28694] ERROR -- : natswrapper.rb:145:in `block in start' Error in NATS connection: OpenSSL::SSL::SSLError: SSL_connect returned=1 errno=0 state=unknown state: wrong version number
E, [2017-07-06T01:03:27.684992 #28694] ERROR -- : natswrapper.rb:145:in `block in start' Error in NATS connection: Errno::ECONNRESET: Connection reset by peer - SSL_connect
W, [2017-07-06T01:03:33.483329 #28694]  WARN -- : natswrapper.rb:131:in `block in start' Reconnected after connection failure: nats://nats.localhost:4222
E, [2017-07-06T01:03:48.807881 #28694] ERROR -- : natswrapper.rb:145:in `block in start' Error in NATS connection: Errno::ECONNRESET: Connection reset by peer
W, [2017-07-06T01:03:48.808237 #28694]  WARN -- : natswrapper.rb:138:in `block in start' Disconnected from NATS: Errno::ECONNRESET: Connection reset by peer
E, [2017-07-06T01:03:51.810184 #28694] ERROR -- : natswrapper.rb:145:in `block in start' Error in NATS connection: NATS::IO::SocketTimeoutError: NATS::IO::SocketTimeoutError
W, [2017-07-06T01:03:56.707405 #28694]  WARN -- : natswrapper.rb:131:in `block in start' Reconnected after connection failure: nats://nats.localhost:4222
E, [2017-07-06T01:04:14.147977 #28694] ERROR -- : natswrapper.rb:145:in `block in start' Error in NATS connection: Errno::ECONNRESET: Connection reset by peer
W, [2017-07-06T01:04:14.148317 #28694]  WARN -- : natswrapper.rb:138:in `block in start' Disconnected from NATS: Errno::ECONNRESET: Connection reset by peer
W, [2017-07-06T01:04:18.492006 #28694]  WARN -- : natswrapper.rb:131:in `block in start' Reconnected after connection failure: nats://nats.localhost:4222
E, [2017-07-06T01:09:28.741259 #28694] ERROR -- : natswrapper.rb:145:in `block in start' Error in NATS connection: Errno::ECONNRESET: Connection reset by peer
W, [2017-07-06T01:09:28.741613 #28694]  WARN -- : natswrapper.rb:138:in `block in start' Disconnected from NATS: Errno::ECONNRESET: Connection reset by peer
W, [2017-07-06T01:09:32.776621 #28694]  WARN -- : natswrapper.rb:131:in `block in start' Reconnected after connection failure: nats://nats.localhost:4222
E, [2017-07-06T01:09:49.439548 #28694] ERROR -- : natswrapper.rb:145:in `block in start' Error in NATS connection: Errno::ECONNRESET: Connection reset by peer
W, [2017-07-06T01:09:49.439757 #28694]  WARN -- : natswrapper.rb:138:in `block in start' Disconnected from NATS: Errno::ECONNRESET: Connection reset by peer
E, [2017-07-06T01:09:54.943099 #28694] ERROR -- : natswrapper.rb:145:in `block in start' Error in NATS connection: OpenSSL::SSL::SSLError: SSL_connect returned=1 errno=0 state=unknown state: wrong version number
W, [2017-07-06T01:09:59.456253 #28694]  WARN -- : natswrapper.rb:131:in `block in start' Reconnected after connection failure: nats://nats.localhost:4222
E, [2017-07-06T01:10:18.826265 #28694] ERROR -- : natswrapper.rb:145:in `block in start' Error in NATS connection: Errno::ECONNRESET: Connection reset by peer
W, [2017-07-06T01:10:18.826473 #28694]  WARN -- : natswrapper.rb:138:in `block in start' Disconnected from NATS: Errno::ECONNRESET: Connection reset by peer
W, [2017-07-06T01:10:27.312631 #28694]  WARN -- : natswrapper.rb:131:in `block in start' Reconnected after connection failure: nats://nats.localhost:4222
E, [2017-07-06T01:11:29.631761 #28694] ERROR -- : natswrapper.rb:145:in `block in start' Error in NATS connection: Errno::ECONNRESET: Connection reset by peer
W, [2017-07-06T01:11:29.631969 #28694]  WARN -- : natswrapper.rb:138:in `block in start' Disconnected from NATS: Errno::ECONNRESET: Connection reset by peer
E, [2017-07-06T01:11:32.634813 #28694] ERROR -- : natswrapper.rb:145:in `block in start' Error in NATS connection: NATS::IO::SocketTimeoutError: NATS::IO::SocketTimeoutError
W, [2017-07-06T01:11:37.240571 #28694]  WARN -- : natswrapper.rb:131:in `block in start' Reconnected after connection failure: nats://nats.localhost:4222
E, [2017-07-06T01:11:58.848315 #28694] ERROR -- : natswrapper.rb:145:in `block in start' Error in NATS connection: Errno::ECONNRESET: Connection reset by peer
W, [2017-07-06T01:11:58.848524 #28694]  WARN -- : natswrapper.rb:138:in `block in start' Disconnected from NATS: Errno::ECONNRESET: Connection reset by peer
E, [2017-07-06T01:12:02.643977 #28694] ERROR -- : natswrapper.rb:145:in `block in start' Error in NATS connection: OpenSSL::SSL::SSLError: SSL_connect returned=1 errno=0 state=unknown state: wrong version number
E, [2017-07-06T01:12:05.646686 #28694] ERROR -- : natswrapper.rb:145:in `block in start' Error in NATS connection: NATS::IO::SocketTimeoutError: NATS::IO::SocketTimeoutError
E, [2017-07-06T01:12:08.649694 #28694] ERROR -- : natswrapper.rb:145:in `block in start' Error in NATS connection: NATS::IO::SocketTimeoutError: NATS::IO::SocketTimeoutError
E, [2017-07-06T01:12:14.142892 #28694] ERROR -- : natswrapper.rb:145:in `block in start' Error in NATS connection: OpenSSL::SSL::SSLError: SSL_connect returned=1 errno=0 state=unknown state: wrong version number
E, [2017-07-06T01:12:19.648892 #28694] ERROR -- : natswrapper.rb:145:in `block in start' Error in NATS connection: OpenSSL::SSL::SSLError: SSL_connect returned=1 errno=0 state=unknown state: wrong version number
E, [2017-07-06T01:12:25.517360 #28694] ERROR -- : natswrapper.rb:145:in `block in start' Error in NATS connection: OpenSSL::SSL::SSLError: SSL_connect returned=1 errno=0 state=unknown state: wrong version number
E, [2017-07-06T01:12:33.344220 #28694] ERROR -- : natswrapper.rb:145:in `block in start' Error in NATS connection: OpenSSL::SSL::SSLError: SSL_connect returned=1 errno=0 state=unknown state: wrong version number
E, [2017-07-06T01:12:37.974677 #28694] ERROR -- : natswrapper.rb:145:in `block in start' Error in NATS connection: OpenSSL::SSL::SSLError: SSL_connect returned=1 errno=0 state=unknown state: wrong version number
E, [2017-07-06T01:12:44.444605 #28694] ERROR -- : natswrapper.rb:145:in `block in start' Error in NATS connection: OpenSSL::SSL::SSLError: SSL_connect returned=1 errno=0 state=unknown state: wrong version number
E, [2017-07-06T01:12:49.104963 #28694] ERROR -- : natswrapper.rb:145:in `block in start' Error in NATS connection: OpenSSL::SSL::SSLError: SSL_connect returned=1 errno=0 state=unknown state: wrong version number
E, [2017-07-06T01:12:53.735184 #28694] ERROR -- : natswrapper.rb:145:in `block in start' Error in NATS connection: OpenSSL::SSL::SSLError: SSL_connect returned=1 errno=0 state=unknown state: wrong version number
E, [2017-07-06T01:12:58.943338 #28694] ERROR -- : natswrapper.rb:145:in `block in start' Error in NATS connection: OpenSSL::SSL::SSLError: SSL_connect returned=1 errno=0 state=unknown state: wrong version number
E, [2017-07-06T01:13:01.946024 #28694] ERROR -- : natswrapper.rb:145:in `block in start' Error in NATS connection: NATS::IO::SocketTimeoutError: NATS::IO::SocketTimeoutError
E, [2017-07-06T01:13:06.364613 #28694] ERROR -- : natswrapper.rb:145:in `block in start' Error in NATS connection: NATS::IO::SocketTimeoutError: NATS::IO::SocketTimeoutError
E, [2017-07-06T01:13:11.816025 #28694] ERROR -- : natswrapper.rb:145:in `block in start' Error in NATS connection: OpenSSL::SSL::SSLError: SSL_connect returned=1 errno=0 state=unknown state: wrong version number
E, [2017-07-06T01:13:17.724982 #28694] ERROR -- : natswrapper.rb:145:in `block in start' Error in NATS connection: OpenSSL::SSL::SSLError: SSL_connect returned=1 errno=0 state=unknown state: wrong version number
E, [2017-07-06T01:13:21.673088 #28694] ERROR -- : natswrapper.rb:145:in `block in start' Error in NATS connection: Errno::ECONNRESET: Connection reset by peer - SSL_connect
E, [2017-07-06T01:13:28.502194 #28694] ERROR -- : natswrapper.rb:145:in `block in start' Error in NATS connection: OpenSSL::SSL::SSLError: SSL_connect returned=1 errno=0 state=unknown state: wrong version number
E, [2017-07-06T01:13:38.569249 #28694] ERROR -- : natswrapper.rb:145:in `block in start' Error in NATS connection: NATS::IO::SocketTimeoutError: NATS::IO::SocketTimeoutError
E, [2017-07-06T01:13:43.363746 #28694] ERROR -- : natswrapper.rb:145:in `block in start' Error in NATS connection: Errno::ECONNRESET: Connection reset by peer - SSL_connect
W, [2017-07-06T01:13:49.054190 #28694]  WARN -- : natswrapper.rb:131:in `block in start' Reconnected after connection failure: nats://nats.localhost:4222
E, [2017-07-06T01:14:09.699841 #28694] ERROR -- : natswrapper.rb:145:in `block in start' Error in NATS connection: Errno::ECONNRESET: Connection reset by peer
W, [2017-07-06T01:14:09.700045 #28694]  WARN -- : natswrapper.rb:138:in `block in start' Disconnected from NATS: Errno::ECONNRESET: Connection reset by peer
E, [2017-07-06T01:14:15.122683 #28694] ERROR -- : natswrapper.rb:145:in `block in start' Error in NATS connection: OpenSSL::SSL::SSLError: SSL_connect returned=1 errno=0 state=unknown state: wrong version number
E, [2017-07-06T01:14:39.412322 #28694] ERROR -- : natswrapper.rb:145:in `block in start' Error in NATS connection: OpenSSL::SSL::SSLError: SSL_connect returned=1 errno=0 state=unknown state: wrong version number
```

**Comment by ripienaar** [comment]
closing this, we have an entirely new federation broker and the ruby one is now deprecated

**Comment by mateusz-gozdek-sociomantic** [comment]
I couldn't find any reference to new federation broker, either in current docs or in modules changelog. Can you give me a reference to it? How do I migrate to new federation broker?

**Comment by ripienaar** [comment]
@mateusz-gozdek-sociomantic it will ship in the next release, see https://master.choria.io/docs/federation/ for a doc preview

**Comment by mateusz-gozdek-sociomantic** [comment]
I see. So "we have" meaning that old federation broker is deprecated and will be replaced in future release. It wasn't clear for me.  Thanks for quick clarification!

**Comment by ripienaar** [comment]
yup, you can grab master of `choria-io/puppet-choria` and have it today, its all ready to go :)
