### ISSUE TITLE
Some extra paths needed

### ISSUE THREAD

**Issue by lofic** [choria-io/mcollective-choria#505]
Puppet tasks assume some paths, like in puppetlabs-apache : 

stdout, _stderr, _status = Open3.capture3('facter', '-p', 'osfamily')

This fails when the tasks are run with choria : 

```
$ mco tasks run apache --action reload -W hostname=sandbox01 --timeout 10
Retrieving task metadata for task apache from the Puppet Server
Attempting to download and run task apache on 1 nodes

Downloading and verifying 1 file(s) from the Puppet Server to all nodes: ✓  1 / 1

Running task apache and waiting up to 60 seconds for it to complete

sandbox01.labolinux.fr          choria.tasks/task-error: The task errored with a code 1
   {"_output":""}
   /opt/puppetlabs/puppet/lib/ruby/2.4.0/open3.rb:199:in `spawn': No such file or directory - facter (Errno::ENOENT)
	from /opt/puppetlabs/puppet/lib/ruby/2.4.0/open3.rb:199:in `popen_run'
	from /opt/puppetlabs/puppet/lib/ruby/2.4.0/open3.rb:95:in `popen3'
	from /opt/puppetlabs/puppet/lib/ruby/2.4.0/open3.rb:258:in `capture3'
	from /opt/puppetlabs/mcollective/tasks-cache/96ad16288edceb12452d0372196249941da082fba81126e9a4953e12678fc31d/init.rb:8:in `service'
	from /opt/puppetlabs/mcollective/tasks-cache/96ad16288edceb12452d0372196249941da082fba81126e9a4953e12678fc31d/init.rb:28:in `<main>'
```

**Comment by ripienaar** [comment]
agree this is needed, have asked Puppet if they feel like specifying this clearly in the spec so different implementations can be portable

**Comment by ripienaar** [comment]
Closing as upstream issue
