### ISSUE TITLE
Mcollective not reconnecting to broker after stale connection

### ISSUE THREAD

**Issue by mateusz-gozdek-sociomantic** [choria-io/mcollective-choria#516]
So here is what I got when we had some network issues:
```
E, [2018-07-02T15:18:30.270432+00:00 #12076] ERROR -- : natswrapper.rb:145:in `block in start' Error in NATS connection: NATS::IO::StaleConnectionError: nats: stale connection
W, [2018-07-02T15:18:30.270696+00:00 #12076]  WARN -- : natswrapper.rb:138:in `block in start' Disconnected from NATS: NATS::IO::StaleConnectionError: nats: stale connection
```

And after that, it never reconnected until I restarted mcollective.

By looking at: https://github.com/choria-io/mcollective-choria/blob/078a093374cb600f64ead83be890c56cee348134/lib/mcollective/util/natswrapper.rb#L165 and https://github.com/nats-io/ruby-nats/issues/143#issuecomment-352863859 I'm thinking that maybe solution from https://stackoverflow.com/a/4975796 should be used instead to prevent that.

Also capture from `strace`:
```
futex(0x2503694, FUTEX_WAIT_BITSET_PRIVATE, 9850657, {7229043, 678070576}, ffffffff) = -1 ETIMEDOUT (Connection timed out)
futex(0x2503708, FUTEX_WAKE_PRIVATE, 1) = 0
futex(0x2503694, FUTEX_WAIT_BITSET_PRIVATE, 9850659, {7229043, 778228912}, ffffffff) = -1 ETIMEDOUT (Connection timed out)
futex(0x2503708, FUTEX_WAKE_PRIVATE, 1) = 0
futex(0x2503694, FUTEX_WAIT_BITSET_PRIVATE, 9850661, {7229043, 878461309}, ffffffff) = -1 ETIMEDOUT (Connection timed out)
futex(0x2503708, FUTEX_WAKE_PRIVATE, 1) = 0
futex(0x2503694, FUTEX_WAIT_BITSET_PRIVATE, 9850663, {7229043, 978576582}, ffffffff) = -1 ETIMEDOUT (Connection timed out)
futex(0x2503708, FUTEX_WAKE_PRIVATE, 1) = 0
futex(0x2503694, FUTEX_WAIT_BITSET_PRIVATE, 9850665, {7229044, 78692445}, ffffffff) = -1 ETIMEDOUT (Connection timed out)
futex(0x2503708, FUTEX_WAKE_PRIVATE, 1) = 0
futex(0x2503694, FUTEX_WAIT_BITSET_PRIVATE, 9850667, {7229044, 178933081}, ffffffff) = -1 ETIMEDOUT (Connection timed out)
futex(0x2503708, FUTEX_WAKE_PRIVATE, 1) = 0
futex(0x2503694, FUTEX_WAIT_BITSET_PRIVATE, 9850669, {7229044, 279275921}, ffffffff) = -1 ETIMEDOUT (Connection timed out)
futex(0x2503708, FUTEX_WAKE_PRIVATE, 1) = 0
write(6, "!", 1)                        = 1
futex(0x2502f64, FUTEX_WAIT_PRIVATE, 123735, NULL) = 0
futex(0x2502f9c, FUTEX_WAKE_OP_PRIVATE, 1, 1, 0x2502f98, {FUTEX_OP_SET, 0, FUTEX_OP_CMP_GT, 1}) = 1
futex(0x2502f30, FUTEX_WAKE_PRIVATE, 1) = 0
futex(0x2503694, FUTEX_WAIT_BITSET_PRIVATE, 9850671, {7229044, 389339479}, ffffffff) = -1 ETIMEDOUT (Connection timed out)
futex(0x2503708, FUTEX_WAKE_PRIVATE, 1) = 0
futex(0x2503694, FUTEX_WAIT_BITSET_PRIVATE, 9850673, {7229044, 489449391}, ffffffff) = -1 ETIMEDOUT (Connection timed out)
futex(0x2503708, FUTEX_WAKE_PRIVATE, 1) = 0
futex(0x2503694, FUTEX_WAIT_BITSET_PRIVATE, 9850675, {7229044, 589560199}, ffffffff) = -1 ETIMEDOUT (Connection timed out)
futex(0x2503708, FUTEX_WAKE_PRIVATE, 1) = 0
futex(0x2503694, FUTEX_WAIT_BITSET_PRIVATE, 9850677, {7229044, 689703399}, ffffffff) = -1 ETIMEDOUT (Connection timed out)
```

**Comment by mateusz-gozdek-sociomantic** [comment]
```
# /opt/puppetlabs/puppet/bin/gem list

*** LOCAL GEMS ***

bigdecimal (default: 1.3.2)
deep_merge (1.0.1)
did_you_mean (1.1.0)
facter (3.11.2)
fast_gettext (1.1.2)
gettext (3.2.2)
gettext-setup (0.30)
hiera (3.4.3)
hiera-eyaml (2.1.0)
highline (1.6.21)
hocon (1.2.5)
io-console (default: 0.4.6)
json (default: 2.0.4)
locale (2.1.2)
minitest (5.10.1)
msgpack (1.1.0)
multi_json (1.13.1)
nats-pure (0.5.0, 0.4.0, 0.3.0, 0.2.4, 0.2.2)
net-ssh (4.2.0)
net-telnet (0.1.1)
openssl (default: 2.0.7)
power_assert (0.4.1)
psych (default: 2.2.2)
puppet (5.5.0)
rake (12.0.0)
rdoc (default: 5.0.0)
semantic_puppet (0.1.2)
stomp (1.4.4)
test-unit (3.2.3)
text (1.3.1)
trollop (2.1.2)
xmlrpc (0.2.1)
```

Perhaps `nats-pure` versions needs some cleaning, I thought some module is already taking care of that.

**Comment by ripienaar** [comment]
it does not remove - only add, puppet "feature"

But that's fine it should therefor be using the right one thats not the event machine based on you found the comment in.

I'll need to investigate what else it can be

**Comment by ripienaar** [comment]
closing this as related to now defunct mcollectived
