### ISSUE TITLE
Windows: Cannot execute Bolt tasks as the node does not meet the minimum compatability requirements

### ISSUE THREAD

**Issue by tccain** [choria-io/mcollective-choria#530]
I have 4 hosts, 3 linux and 1 windows. 

All puppet agents are 5.5.4 (running mcollectived (2.12.2) server, not choria server if that matters)

Puppet Server is 5.3.0

Going through documentation trying to get tasks working and I'm running the command: 

 mco tasks run mcollective_agent_bolt_tasks::ping --message "Hello"

The 3 linux hosts work fine, but the windows hosts returns an error:

```
Retrieving task metadata for task mcollective_agent_bolt_tasks::ping from the Puppet Server
Attempting to download and run task mcollective_agent_bolt_tasks::ping on 4 nodes

Downloading and verifying 1 file(s) from the Puppet Server to all nodes: ✓  4 / 4

Running task mcollective_agent_bolt_tasks::ping and waiting up to 60 seconds for it to complete

<winhost>       Cannot execute Bolt tasks as the node does not meet the minimum compatability requirements



Summary for task e540262f1adb5657b1f660c9ac990aa4

                       Task Name: mcollective_agent_bolt_tasks::ping
                          Caller: choria=mco.mcollective
                       Completed: 3
                         Running: 0
                 Wrapper Failure: 1

                      Successful: 3
                          Failed: 1

                Average Run Time: 0.14s
```

I am wondering if Windows is not supported for tasks or if this agent only works with Choria Server running on the node.

Error logs in mcollective daemon say the following:

```
I, [2018-08-20T14:27:56.145315-04:00 #1032]  INFO -- : runner.rb:216:in `agentmsg' Handling message e540262f1adb5657b1f660c9ac990aa4 for agent 'bolt_tasks' in collective 'mcollective' from choria=mco.mcollective@<client>: {"agent"=>"bolt_tasks", "action"=>"run_and_wait", "caller"=>"choria=mco.mcollective", "data"=>{"task"=>"mcollective_agent_bolt_tasks::ping", "files"=>"[{\"filename\":\"ping.rb\",\"sha256\":\"328716f02f7e45faf53ec842af2e6893af7cd29f6b7de9f69f0a6aeeaa417c9a\",\"size_bytes\":123,\"uri\":{\"path\":\"/puppet/v3/file_content/tasks/mcollective_agent_bolt_tasks/ping.rb\",\"params\":{\"environment\":\"production\"}}}]", "input"=>"{\"message\":\"Hello\"}"}}
E, [2018-08-20T14:27:56.160914-04:00 #1032] ERROR -- : agent.rb:103:in `rescue in handlemsg' bolt_tasks#run_and_wait failed: MCollective::UnknownRPCError: Cannot execute Bolt tasks as the node does not meet the minimum compatability requirements
E, [2018-08-20T14:27:56.160914-04:00 #1032] ERROR -- : agent.rb:104:in `rescue in handlemsg' C:/Program Files/Puppet Labs/Puppet/mcollective/lib/mcollective/rpc/reply.rb:60:in `fail!'
	C:/ProgramData/PuppetLabs/mcollective/plugins/mcollective/agent/bolt_tasks.rb:31:in `block in <class:Bolt_tasks>'
	C:/Program Files/Puppet Labs/Puppet/mcollective/lib/mcollective/rpc/agent.rb:86:in `handlemsg'
	C:/Program Files/Puppet Labs/Puppet/mcollective/lib/mcollective/agents.rb:126:in `block (2 levels) in dispatch'
	C:/Program Files/Puppet Labs/Puppet/sys/ruby/lib/ruby/2.4.0/timeout.rb:93:in `block in timeout'
	C:/Program Files/Puppet Labs/Puppet/sys/ruby/lib/ruby/2.4.0/timeout.rb:33:in `block in catch'
	C:/Program Files/Puppet Labs/Puppet/sys/ruby/lib/ruby/2.4.0/timeout.rb:33:in `catch'
	C:/Program Files/Puppet Labs/Puppet/sys/ruby/lib/ruby/2.4.0/timeout.rb:33:in `catch'
	C:/Program Files/Puppet Labs/Puppet/sys/ruby/lib/ruby/2.4.0/timeout.rb:108:in `timeout'
	C:/Program Files/Puppet Labs/Puppet/mcollective/lib/mcollective/agents.rb:125:in `block in dispatch'
```

**Comment by ripienaar** [comment]
Where on your windows machine is `task_wrapper.exe`?

Apart from that this wont work as tasks does not really have a concept (yet) of piking different executables for different operating systems magically, they are working on it but afaik not available yet so you need different task invokes for different OS.

**Comment by tccain** [comment]
That file doesn't seem to exist. Looking at the code it should be: C:\Program Files\Puppet Labs\Puppet\bin\ and it's there on my linux servers, but not Windows.

My problem is definitely not an issue with this project. I'm just missing a file or package on my Windows box. It doesn't seem to be included with Puppet-agent package. 

Any idea which package for windows contains this?

**Comment by ripienaar** [comment]
Code on my side might be wrong. Can you do a file find?

**Comment by tccain** [comment]
Actually it's here: ```C:\Program Files\Puppet Labs\Puppet\pxp-agent\bin\```

**Comment by ripienaar** [comment]
Ok - then I need to do a little update

**Comment by tccain** [comment]
Thanks for the quick response. It seems this is related to https://github.com/choria-io/mcollective-choria/issues/528

The difference being that @smortex suggests adding a list of static paths that could contain task_wrapper.exe, however the list of static paths doesn't include 'C:\Program Files\Puppet Labs\Puppet\pxp-agent\bin\' in it.

I like the commit https://github.com/smortex/mcollective-choria/commit/2e3f914890a551e9de1d8e53cef423302329d7e9 because it looks like I would be able to manually specify the path to the pxp-agent bin directory and I could just  make the change on individual hosts if I needed to.

**Comment by ripienaar** [comment]
Indeed, though we should fix the actual problem - by looking in the right bin dir by default.  We cant expect people to keep configuring it when its mostly in the same place.

I'll get that in for next release
