### ISSUE TITLE
Intermediate cert chains

### ISSUE THREAD

**Issue by vjanelle** [choria-io/mcollective-choria#550]
The mco client / ruby openssl can't work with client certificates that have intermediate CA chains present in the file.

A common workaround in other projects has been something like:

```ruby
         extra_chain_cert = File.read(client_public_cert).lines.reject { |line|
             line[0] == '#'
         }.join('').scan(/(-----BEGIN CERTIFICATE-----.+?-----END CERTIFICATE-----)/m).drop(1).map {|cstr| OpenSSL::X509::Certificate.new(cstr[0])}
 
         context.extra_chain_cert = extra_chain_cert
```

Possibly somewhere around https://github.com/choria-io/mcollective-choria/blob/f8d6e13efc103e3e8a83f034f4be8da858cd1503/lib/mcollective/util/choria.rb#L643

(The above snippet Worked For Me™, but I didn't add tests around it.)

**Comment by ripienaar** [comment]
`extra_chain_cert` is apparently deprecated it says to use `add_certificate` multiple times instead.

https://ruby.github.io/openssl/OpenSSL/SSL/SSLContext.html#attribute-i-extra_chain_cert

**Comment by vjanelle** [comment]
@ripienaar unless you're using the version of ruby in the choria-demo vm:

```
[vagrant@puppet ~]$ mco ping -v

The ping application failed to run: undefined method `add_certificate' for #<OpenSSL::SSL::SSLContext:0x00000000025e6260>

undefined method `add_certificate' for #<OpenSSL::SSL::SSLContext:0x00000000025e6260> (NoMethodError)
	from /opt/puppetlabs/mcollective/plugins/mcollective/util/choria.rb:652:in `ssl_context'  <----
	from /opt/puppetlabs/mcollective/plugins/mcollective/connector/nats.rb:76:in `connect'
	from /opt/puppetlabs/puppet/lib/ruby/vendor_ruby/mcollective/client.rb:36:in `block in initialize'
	from /opt/puppetlabs/puppet/lib/ruby/2.4.0/timeout.rb:93:in `block in timeout'
	from /opt/puppetlabs/puppet/lib/ruby/2.4.0/timeout.rb:103:in `timeout'
	from /opt/puppetlabs/puppet/lib/ruby/vendor_ruby/mcollective/client.rb:35:in `initialize'
	from /opt/puppetlabs/puppet/lib/ruby/vendor_ruby/mcollective/application/ping.rb:57:in `new'
	from /opt/puppetlabs/puppet/lib/ruby/vendor_ruby/mcollective/application/ping.rb:57:in `main'
	from /opt/puppetlabs/puppet/lib/ruby/vendor_ruby/mcollective/application.rb:293:in `run'
	from /opt/puppetlabs/puppet/lib/ruby/vendor_ruby/mcollective/applications.rb:23:in `run'
	from /opt/puppetlabs/puppet/bin/mco:33:in `<main>'
```

**Comment by vjanelle** [comment]
Need to generate tests for this, will do so tomorrow.  Let me know if this looks ok.

**Comment by vjanelle** [comment]
This one is failing for me on the master branch:

```
 1) MCollective::Util::BoltSupport#run_task should support fail_ok
     Failure/Error:
       expect { support.run_task(nil, "shell", "command" => "/bin/false") }.to raise_error(
         "Command failed with code 1"
       )

       expected Exception with "Command failed with code 1", got #<RuntimeError: Command failed with code 42> with backtrace:
         # ./lib/mcollective/util/bolt_support.rb:165:in `run_task'
         # ./spec/unit/mcollective/util/bolt_support_spec.rb:63:in `block (4 levels) in <module:Util>'
         # ./spec/unit/mcollective/util/bolt_support_spec.rb:63:in `block (3 levels) in <module:Util>'
     # ./spec/unit/mcollective/util/bolt_support_spec.rb:63:in `block (3 levels) in <module:Util>'
```

**Comment by vjanelle** [comment]
Turns out /bin/false doesn't exist on a mac.  Good to know!
